try:
    a= int(input("enter number"))

except Exception as e:
    print(e)

else:
    print("all done")

# finally:
#     print ("finally")

